// <auto-generated />
namespace temWebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MT4TradeViewModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MT4TradeViewModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201609260755008_MT4TradeViewModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
